<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>diacomp</groupId>
	<artifactId>root</artifactId>
	<version>0.2.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<modules>
		<module>comp-transfer</module>
		<module>comp-server-core</module>
		<module>comp-server</module>
		<module>comp-server-rest</module>
	</modules>

	<properties>
		<java.version>1.8</java.version>
		<maven.source.version>1.8</maven.source.version>
		<maven.compile.version>1.8</maven.compile.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
</project>